# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_dissimilarities_cpp <- function(data1, data2, var_types, scaling) {
    .Call(`_gowerpmm_compute_dissimilarities_cpp`, data1, data2, var_types, scaling)
}

#' Objective Function for Gower Weight Optimization (C++)
#'
#' This is the core fitness function for the Genetic Algorithm. It computes
#' the negative standard deviation of the rank correlations between each
#' single-variable dissimilarity and the final weighted Gower dissimilarity.
#'
#' @param weights A numeric vector of weights.
#' @param dissim_matrices A 3D cube where each slice is a vectorized
#'        dissimilarity matrix for a single variable.
#' @return The fitness value (to be maximized by GA).
objective_function_cpp <- function(weights_r, dissim_matrices) {
    .Call(`_gowerpmm_objective_function_cpp`, weights_r, dissim_matrices)
}

get_rank_correlations_cpp <- function(weights_r, dissim_matrices) {
    .Call(`_gowerpmm_get_rank_correlations_cpp`, weights_r, dissim_matrices)
}

#' Spearman's Rank Correlation (C++)
#'
#' A high-performance C++ implementation of Spearman's rank correlation.
#' @param x A numeric vector.
#' @param y A numeric vector.
#' @return The Spearman's correlation coefficient.
spearman_correlation_cpp <- function(x, y) {
    .Call(`_gowerpmm_spearman_correlation_cpp`, x, y)
}

